name: Build NG-GL4ES
on: [workflow_dispatch,push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Android NDK
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d $HOME >> /dev/null
      - name: Build Krypton Wrapper
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake

          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -DCMAKE_CXX_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/usr/bin/make
          cmake --build .
      - name: Upload Krypton Wrapper libs
        uses: actions/upload-artifact@v3
        with:
          name: KryptonWrapper-android
          path: libs/*