name: Build gl4es-114
on: [workflow_dispatch,push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build GL4ES
        run: |
          cmake --build .
      - name: Upload GL4ES libs
        uses: actions/upload-artifact@v4
        with:
          name: gl4es-114-android
          path: libs/*
