name: Build gl4es-114
on: [workflow_dispatch,push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build GL4ES
        run: |
         # wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
         # unzip android-ndk-r25c-linux.zip >> /dev/null
         $ANDROID_NDK_HOME/ndk-build APP_BUILD_SCRIPT=./Android.mk APP_PLATFORM=24 NDK_PROJECT_PATH=.
      - name: Upload GL4ES libs
        uses: actions/upload-artifact@v4
        with:
          name: gl4es-114-android
          path: libs/*
