name: C/C++ CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      shell: bash
      run: cmake --build . --config ${{ matrix.build_type }} --target install ${{ env.PARALLEL }}
    - name: Upload GL4ES libs
      uses: actions/upload-artifact@v4
      with:
       name: gl4es-114-android
       path: libs/*
